<a href="https://colab.research.google.com/github/ondalnight/Bigdata/blob/main/code/03w_numpy_handle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a = np.power(np.arange(10), 2)
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [3]:
a[3]

np.int64(9)

In [4]:
int(a[3])

9

In [5]:
a[-2]

np.int64(64)

In [6]:
a[1:4]

array([1, 4, 9])

In [7]:
a[-5:-1]

array([25, 36, 49, 64])

In [8]:
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [9]:
a[8:2:-2]

array([64, 36, 16])

In [11]:
a = np.arange(24).reshape(2, 3, 4)

In [13]:
a.reshape(3, 2, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [14]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [16]:
a[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
a[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [20]:
a[:, 1]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [21]:
a[:, 1, 1]

array([ 5, 17])

In [24]:
a


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [23]:
a[:, :]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [25]:
a[:, :, 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [26]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [27]:
a[:]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [28]:
a[..., 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [29]:
a[1, ..., 1]

array([13, 17, 21])

In [30]:
a[1, :, 1]

array([13, 17, 21])

In [31]:
a[0,...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
a[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
a = np.arange(1, 7).reshape(2, 3)

In [46]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [47]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [48]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [49]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
a= np.array([3,4,5,6])
b= np.array([1,2,3,4])


a * b

array([ 3,  8, 15, 24])

#고급 색인

In [54]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
x[1]

np.int64(1)

In [56]:
x[:5]

array([0, 1, 2, 3, 4])

In [57]:
x[ [1] ]

array([1])

In [58]:
x[ [1, 1, 2, 5] ]

array([1, 1, 2, 5])

In [60]:
x[ [1, 1, 2, 5, -1, -2, -5, -10] ]

array([1, 1, 2, 5, 9, 8, 5, 0])

In [61]:
x = np.arange(56).reshape(7, 8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [62]:
x[0]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [63]:
x[5]

array([40, 41, 42, 43, 44, 45, 46, 47])

In [64]:
x[ [5,6] ]

array([[40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [65]:
x[0, 1]

np.int64(1)

In [66]:
x[ [0, 1] ]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [68]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [67]:
x[:, 2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [69]:
x[0, 1]

np.int64(1)

In [71]:
x[[0] , [1]]

array([1])

In [72]:
x[:, [1]]

array([[ 1],
       [ 9],
       [17],
       [25],
       [33],
       [41],
       [49]])

In [73]:
x[:, [5, 4]]


array([[ 5,  4],
       [13, 12],
       [21, 20],
       [29, 28],
       [37, 36],
       [45, 44],
       [53, 52]])

In [74]:
x[:, [4, 5]]



array([[ 4,  5],
       [12, 13],
       [20, 21],
       [28, 29],
       [36, 37],
       [44, 45],
       [52, 53]])

In [75]:
x[[1,3]]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [76]:
x[[1,3],:]


array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [77]:
x[[1],[2]]


array([10])

In [78]:
x[[1,3],[2,2]]


array([10, 26])

In [79]:
x[[1,3],[2]]



array([10, 26])

In [80]:
x[[1,3],2]


array([10, 26])

In [81]:
x[[0,2,4],1]


array([ 1, 17, 33])

In [82]:
x[[0,2,4],:2]


array([[ 0,  1],
       [16, 17],
       [32, 33]])

In [83]:
x[[0,2,4],2]


array([ 2, 18, 34])

In [84]:
x[[0,2,4],[0,1,2]]


array([ 0, 17, 34])

In [85]:
a = np.arange(40).reshape(5,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [86]:
a[2:4, 3:7]

array([[19, 20, 21, 22],
       [27, 28, 29, 30]])

In [87]:
a[np.arange(2,4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [88]:
a[[2,3]]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [90]:
a[[2,3,4]]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [94]:
np.arange(2,4)

array([2, 3])

In [93]:
a[ np.arange(2,4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [95]:
a[np.arange(2,4)] [:,[1,0]]

array([[17, 16],
       [25, 24]])

In [96]:
a[np.arange(2,5)] [:,[1,0,3,5]]


array([[17, 16, 19, 21],
       [25, 24, 27, 29],
       [33, 32, 35, 37]])

In [97]:
a[np.arange(2,5)] [:, np.arange(-1, -8, -1)]

array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25],
       [39, 38, 37, 36, 35, 34, 33]])