<a href="https://colab.research.google.com/github/ondalnight/Bigdata/blob/main/code/04w_array_stack_split.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

a = np.arange(1, 13).reshape(3, 4)
c = np.arange(1, 6, 2)

a, c

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([1, 3, 5]))

In [ ]:
c[:, None]

array([[1],
       [3],
       [5]])

In [ ]:
c[:, np.newaxis]

array([[1],
       [3],
       [5]])

In [ ]:
cc = np.expand_dims(c, axis = 1)

In [ ]:
np.hstack((a, cc))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [ ]:
np.column_stack((a, c))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [ ]:
np.column_stack((a, cc))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [ ]:
a = np.arange(1, 4)
b = np.arange(4, 7)
a, b

(array([1, 2, 3]), array([4, 5, 6]))

In [ ]:
np.c_[a, b], np.c_[(a, b)]

(array([[1, 4],
        [2, 5],
        [3, 6]]),
 array([[1, 4],
        [2, 5],
        [3, 6]]))

In [ ]:
np.c_[a, b], np.column_stack((a, b))

(array([[1, 4],
        [2, 5],
        [3, 6]]),
 array([[1, 4],
        [2, 5],
        [3, 6]]))

In [ ]:
x = np.arange(1, 4).reshape(1, 3)
y = np.arange(4, 7).reshape(1, 3)
x, y

(array([[1, 2, 3]]), array([[4, 5, 6]]))

In [ ]:
np.c_[x, 10, 20, y]

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [ ]:
np.column_stack((x, 10, 20, y))

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

### 난수 기초와 생성


In [ ]:
import numpy as np

rg = np.random.default_rng(12)
rg.random() #(0, 1) 실수 난수

0.2508244581084461

In [ ]:
rg.random()

0.6704457427727847

In [35]:
import numpy as np

rg = np.random.default_rng(12)
rg.integers(1, 7, (3, 4))

array([[4, 2, 6, 6],
       [1, 2, 2, 2],
       [4, 3, 3, 2]])

In [36]:
rg.integers(low = 1, high = 7, size = (3, 4))

array([[6, 5, 4, 1],
       [1, 6, 2, 6],
       [5, 1, 3, 4]])

In [38]:
import numpy as np

rg = np.random.default_rng(12)
rg.standard_normal(10)

array([-0.00682678,  1.04614329,  0.74158842,  0.72395654,  1.61877622,
       -1.20555814, -0.62695547, -1.32066321, -0.10775251,  0.99876366])

In [41]:
rg.standard_normal((3, 4))

array([[-0.02194789,  0.49588007, -1.91076866,  0.14706417],
       [-0.90694325,  1.77538939,  0.88684908,  0.94934948],
       [-0.05785496,  0.61286227,  0.65789016, -0.34440267]])

In [45]:
rg.standard_normal((10 ,5))

array([[-0.58484987,  1.52029173, -0.04495771,  0.4080833 , -0.27031708],
       [-0.08322903,  1.26664783,  0.79599186, -0.08625156,  0.89161997],
       [ 1.07446686, -0.21916602,  0.26998341,  0.25412447, -0.6682962 ],
       [ 1.15087936, -0.16705165, -0.61946934, -1.67579583, -1.26540198],
       [ 1.52542347, -1.1400634 ,  0.42955474, -0.36714608,  0.51132775],
       [ 0.60229717, -0.77628482, -0.29186493,  0.09935615,  0.11454775],
       [-0.02850983, -0.31326723,  0.62940915,  1.31710219,  0.54050497],
       [-0.74013954,  0.39594869,  0.06110415,  0.46162866,  1.84484304],
       [-0.21395332, -0.01150197, -0.88662764, -0.28894863, -0.56915037],
       [ 1.59983162,  0.30397448, -0.57191797,  1.92946911, -1.32814047]])

In [4]:
import numpy as np

n = np.arange(96).reshape(4, 4, 6)
n

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47]],

       [[48, 49, 50, 51, 52, 53],
        [54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65],
        [66, 67, 68, 69, 70, 71]],

       [[72, 73, 74, 75, 76, 77],
        [78, 79, 80, 81, 82, 83],
        [84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95]]])

In [5]:
np.split(n, 2)[1].shape

(2, 4, 6)